---
title: "script"
author: "LAR"
date: "9/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# library
```{r}
library(tidyverse)
library(ggthemes)
```

# data

```{r}
prod <- read.csv("data/production_cec.csv")
```


# plots
## provincial
```{r}
prod$area_ha <- as.numeric(prod$area_ha)

ggplot(prod %>% 
          filter(!is.na(area_ha)),
          aes(x = provabbrev, y = area_ha))+
  geom_boxplot()+
  geom_jitter(data = prod %>% 
                 filter(!is.na(area_ha)), 
              aes(x = provabbrev, y = area_ha), colour = "grey50", size = 2, alpha = 0.6)+
  #scale_y_continuous(labels=function(x){sprintf("%.0f", x)})+
  labs(
    x = "Province",
    y = "Area (hectare)")+
  scale_y_continuous(breaks=seq(0, 400000, 50000))+
  theme_clean(base_size = 16)
ggsave("vis/provincial.png", units = "cm", width = 20, height = 12)
options(scipen=999)
```

## time 
```{r}
prod$year <- as.numeric(prod$year)

str(prod)

prod %>% 
filter(!is.na(area_ha)) %>% 
  group_by(year) %>% 
  dplyr::summarise(total_ha = sum(area_ha))%>% 
  ggplot(aes(year, total_ha))+
  geom_point(shape= 1, size = 4)+ # Use hollow circles
  geom_smooth(method=lm)+ 
  labs(x = "Year", 
       y = "Total Area Planted (ha)",
       caption = "The shaded area represents a 95% confidence region")+
  
  scale_x_continuous(breaks=seq(2006,2021,1))+
  scale_y_continuous(breaks=seq(0, 800000, 100000))+
  theme_clean(base_size = 22)
  ggsave(file="vis/annual.png", units = "cm", width=30, height=18)
options(scipen=999)
```

# growth
```{r}
prod <- prod %>% 
  mutate(t.ha = yield_ton/area_ha) 

prod_avg <- prod %>% 
  group_by(province) %>% 
  summarise(avg_tonnage = mean(t.ha, na.rm = T))


options(scipen=999)
plot1 <- prod %>% select(year, province, t.ha) %>% 
  #filter(province %in% c("Northern Cape", "Eastern Cape", "Western Cape")) %>% 
  ggplot(aes(year, t.ha))+
  geom_point(size = 3)+
    scale_y_continuous(breaks=seq(0, 4, 0.5))+
  #scale_x_continuous(breaks=seq(2006,2021,1))+
  facet_wrap(~province)+
   labs(x = "Year", 
       y = "Tonnage (t.ha)")+
  theme_classic(base_size = 22)

plot1+
  geom_hline(aes(yintercept = avg_tonnage), prod_avg,  linetype = "dashed", color = "red")
ggsave(file="vis/annual_tha_contrasts.png", units = "cm", width=30, height=25)
```

